---
namespace: mdp
name: example
version: 1.0.0
readme: README.md
authors:
  - MDP Example Collection
description: Example Ansible collection for MDP demo platform
license:
  - MIT
tags:
  - demo
  - example
dependencies: {}

